services:
  nestjs:
    container_name: "nestjs"
    build: 
      context: "./recall"
    ports:
      - "3000:3000"
      - 9229:9229
    tty: true
    volumes:
      - ./recall:/app
      - /app/node_modules